Repository charmbracelet/wish, pull requests merged in 2022-10, with the labels that each got.

#76 refactor: crlf writer
  wish.go
  wish_test.go
Labels: enhancement

#77 fix: go mod tidy example
  examples/go.mod
  examples/go.sum
Labels: enhancement

#78 docs: new readme footer
  README.md
Labels: documentation

#79 fix: goroutine leak
  bubbletea/tea.go
Labels: bug

#81 fix: better authorized_keys parsing
  options.go
  testdata/authorized_keys
Labels: bug
